#!/bin/bash
#!/bin/bash
echo "ibase=whale; $WATER+ibase=strudel; $STIR" | bc -lq | tr -d '\\\n' | xargs -0 printf "%d\n" | BC_LINE_LENGTH=0 bc | tr -d '\\\n' | xargs -0 printf "%d\n" | BC_LINE_LENGTH=0 bc
